In [2]:
OPENAI_API_KEY = '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'
# os.environ["ALPHA_VANTAGE_API_KEY"] = os.getenv('ALPHA_VANTAGE_API_KEY')

# TESTING

In [3]:
from langchain.tools import StructuredTool
from langchain.agents import initialize_agent, AgentType
from langchain.chat_models import ChatOpenAI
from langchain.utilities import SerpAPIWrapper
import yfinance as yf
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.tools.convert_to_openai import format_tool_to_openai_function
from langchain.agents.format_scratchpad import format_to_openai_function_messages
from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser
from langchain.agents import AgentExecutor

In [52]:
import numpy as np

In [70]:
def get_asset_price_yahoo(ticker):
    """Make a request to the yfinance API to get the asset price using asset's ticker symbol as input."""
    ticker_data = yf.Ticker(ticker)
    recent = ticker_data.history(period="1d")
    return {"price": recent.iloc[0]["Close"], "currency": ticker_data.info["currency"]}

def get_asset_beta_yahoo(ticker):
    """Make a request to the yfinance API to get the asset beta using asset's ticker symbol as input."""
    ticker_data = yf.Ticker(ticker)
    beta = ticker_data.info.get('beta')
    return beta

def get_user_risk_level():
    """Returns the user's risk level"""
    return 'Moderate'

def get_user_expected_market_return():
    """Returns the user's expected market return"""
    return 0.05

def get_user_risk_free_rate():
    """Returns the user's risk free rate"""
    return 0.03

def get_asset_stddev_yahoo(ticker):
    """Returns the asset's standard deviation. Display it as a percentage."""
    tickerData = yf.download(ticker, start='2020-01-01', end='2023-12-31')
    returns = tickerData['Close'].pct_change()
    volatility = returns.std()
    return volatility

def calculate_asset_expected_return(risk_free_rate, beta, market_return):
    """Calculates the asset's expected return"""
    return risk_free_rate + beta * (market_return - risk_free_rate)

def calculate_asset_sharpe_ratio(expected_asset_return, risk_free_rate, standard_deviation):
    """Calculate the asset's sharpe ratio."""
    return (expected_asset_return - risk_free_rate)/standard_deviation

def get_asset_details(ticker):
    """Gets all the required details of a stock to display to user using asset's ticker symbol as input."""
    beta = get_asset_beta_yahoo(ticker)
    print(ticker)
    print(beta)
    price = get_asset_price_yahoo(ticker)
    standard_deviation = get_asset_stddev_yahoo(ticker)
    risk_level = get_user_risk_level()
    market_return = get_user_expected_market_return()
    risk_free_rate = get_user_risk_free_rate()
    expected_asset_return = calculate_asset_expected_return(risk_free_rate, beta, market_return)
    sharpe_ratio = calculate_asset_sharpe_ratio(expected_asset_return, risk_free_rate, standard_deviation)
    return_dict = {
        "beta": beta, 
        "price": price['price'], 
        "currency": price['currency'],
        "standard_deviation": standard_deviation,
        "user_risk_level": risk_level, 
        "user_market_return": market_return,
        "user_risk_free_rate": risk_free_rate,
        "expected_asset_return": expected_asset_return,
        "sharpe_ratio": sharpe_ratio
    }
    return return_dict

def get_portfolio_stddev(portfolio_assets):
    stock_list = [k for k in portfolio_assets]
    weight_list = [v["weight"] for k,v in portfolio_assets.items()]
    data = yf.download(
        tickers = stock_list,
        start = '2020-01-01',
        end = '2023-12-31'
    )
    prices = data['Adj Close']
    returns = prices.pct_change()

    portfolio = np.array([weight_list])
    print(portfolio)

    covariance = np.cov(returns.fillna(0).T)
    print(covariance)
    portfolio_standard_deviation = np.sqrt(np.dot(np.dot(portfolio, covariance), portfolio.T))
    return portfolio_standard_deviation
    

def get_portfolio_details(ticker_symbols):
    """Returns various details of the portfolio taking a dictionary of key: asset ticker symbols and value: quantity"""
    risk_free_rate = get_user_risk_free_rate()
    portfolio_details = {}
    portfolio_details["Portfolio"] = {}
    portfolio_details["Portfolio"]["asset_value"] = 0
    portfolio_details["Portfolio"]["expected_return"] = 0
    for asset, quantity in ticker_symbols.items():
        portfolio_details[asset] = get_asset_details(asset)
        portfolio_details[asset]["quantity"] = quantity
        # Calculate the total value of the asset in the portfolio
        portfolio_details[asset]["asset_value"] = portfolio_details[asset]["price"] * quantity
        portfolio_details["Portfolio"]["asset_value"] += portfolio_details[asset]["asset_value"]

    # Calculate weight, expected portfolio return, and standard deviation
    for asset in portfolio_details:
        if asset != "Portfolio":
            # Calculate weight of each asset
            portfolio_details[asset]["weight"] = portfolio_details[asset]["price"] * portfolio_details[asset]["quantity"] / portfolio_details["Portfolio"]["asset_value"]

            # Add to expected portfolio return
            portfolio_details["Portfolio"]["expected_return"] += portfolio_details[asset]["expected_asset_return"] * portfolio_details[asset]["weight"]
        else:
            portfolio_details[asset]["weight"] = 1
    
    portfolio_assets = {k : v for k, v in portfolio_details.items() if k != "Portfolio"}
    portfolio_details["Portfolio"]["standard_deviation"] = get_portfolio_stddev(portfolio_assets)

    if portfolio_details["Portfolio"]["standard_deviation"] is not None:
        portfolio_details["Portfolio"]["sharpe_ratio"] = (portfolio_details["Portfolio"]["expected_return"] - risk_free_rate) / portfolio_details["Portfolio"]["standard_deviation"]
    else:
        portfolio_details.sharpe_ratio = "NA"

    return portfolio_details

In [71]:
result = get_portfolio_details({'TSLA': 20, 'AMD': 10})
print(result)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  2 of 2 completed

TSLA
2.316
AMD
1.695
[[0.67901279 0.32098721]]
[[0.00113683 0.00068776]
 [0.00068776 0.00183873]]
{'Portfolio': {'asset_value': 5534.800109863281, 'expected_return': 0.07233333887098968, 'weight': 1, 'standard_deviation': array([[0.03183384]]), 'sharpe_ratio': array([[1.32982186]])}, 'TSLA': {'beta': 2.316, 'price': 187.91000366210938, 'currency': 'USD', 'standard_deviation': 0.042901711341951414, 'user_risk_level': 'Moderate', 'user_market_return': 0.05, 'user_risk_free_rate': 0.03, 'expected_asset_return': 0.07632, 'sharpe_ratio': 1.0796772098623957, 'quantity': 20, 'asset_value': 3758.2000732421875, 'weight': 0.6790127915450629}, 'AMD': {'beta': 1.695, 'price': 177.66000366210938, 'currency': 'USD', 'standard_deviation': 0.0337336196581278, 'user_risk_level': 'Moderate', 'user_market_return': 0.05, 'user_risk_free_rate': 0.03, 'expected_asset_return': 0.06390000000000001, 'sharpe_ratio': 1.0049321817094752, 'quantity': 10, 'asset_value': 1776.6000366210938, 'weight': 0.3209872084549

In [72]:
def chatbot(message):
    # Tools
    search = SerpAPIWrapper(serpapi_api_key="f0627549432dff35aa32fa8aa1f1e606b22aa354d42b459ef7bf42ae4e3fa9e7")
    serp_api_tool = StructuredTool.from_function(search.run)
    # get_asset_price_yahoo_tool = StructuredTool.from_function(get_asset_price_yahoo)
    # get_asset_beta_yahoo_tool = StructuredTool.from_function(get_asset_beta_yahoo)
    get_asset_details_tool = StructuredTool.from_function(get_asset_details)
    get_portfolio_details_tool = StructuredTool.from_function(get_portfolio_details)
    tools = [serp_api_tool, get_asset_details_tool, get_portfolio_details_tool]

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "You are very powerful assistant specialising in financial information given a stock name/ticker. You must give information about all the information of the stock as well as the user",
            ),
            ("user", "{input}"),
            MessagesPlaceholder(variable_name="agent_scratchpad"),
        ]
    )
    llm = ChatOpenAI(temperature = 0.0, openai_api_key="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")
    llm_with_tools = llm.bind(functions=[format_tool_to_openai_function(t) for t in tools])
    agent = (
        {
            "input": lambda x: x["input"],
            "agent_scratchpad": lambda x: format_to_openai_function_messages(
                x["intermediate_steps"]
            ),
        }
        | prompt
        | llm_with_tools
        | OpenAIFunctionsAgentOutputParser()
    )

    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
    #agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

    response = agent_executor.invoke({"input":message})["output"]
    return response

In [74]:
print(chatbot("I have a portfolio with 5 AMD and 3 TSLA"))



> Entering new AgentExecutor chain...


[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  2 of 2 completed


Invoking: `get_portfolio_details` with `{'ticker_symbols': {'AMD': 5, 'TSLA': 3}}`


AMD
1.695
TSLA
2.316
[[0.61176422 0.38823578]]
[[0.00113683 0.00068776]
 [0.00068776 0.00183873]]
{'Portfolio': {'asset_value': 1452.030029296875, 'expected_return': 0.06872188838741895, 'weight': 1, 'standard_deviation': array([[0.03208283]]), 'sharpe_ratio': array([[1.20693499]])}, 'AMD': {'beta': 1.695, 'price': 177.66000366210938, 'currency': 'USD', 'standard_deviation': 0.0337336196581278, 'user_risk_level': 'Moderate', 'user_market_return': 0.05, 'user_risk_free_rate': 0.03, 'expected_asset_return': 0.06390000000000001, 'sharpe_ratio': 1.0049321817094752, 'quantity': 5, 'asset_value': 888.3000183105469, 'weight': 0.6117642200145775}, 'TSLA': {'beta': 2.316, 'price': 187.91000366210938, 'currency': 'USD', 'standard_deviation': 0.042901711341951414, 'user_risk_level': 'Moderate', 'user_market_return': 0.05, 'user_risk_free_rate': 0.03, 'expected_asset_return': 0.07632, 'sharpe_ratio': 1.0796772098

Here are the details of your portfolio:

- AMD:
  - Quantity: 5
  - Price: $177.66
  - Currency: USD
  - Beta: 1.695
  - Standard Deviation: 0.0337
  - Expected Return: 6.39%
  - Sharpe Ratio: 1.00
  - Asset Value: $888.30
  - Weight: 61.18%

- TSLA:
  - Quantity: 3
  - Price: $187.91
  - Currency: USD
  - Beta: 2.316
  - Standard Deviation: 0.0429
  - Expected Return: 7.63%
  - Sharpe Ratio: 1.08
  - Asset Value: $563.73
  - Weight: 38.82%

Overall Portfolio:
- Asset Value: $1452.03
- Expected Return: 6.87%
- Weight: 100%
- Standard Deviation: 0.0321
- Sharpe Ratio: 1.21

Please note that the expected return, standard deviation, and sharpe ratio are calculated based on your risk level, market return, and risk-free rate.

> Finished chain.
Here are the details of your portfolio:

- AMD:
  - Quantity: 5
  - Price: $177.66
  - Currency: USD
  - Beta: 1.695
  - Standard Deviation: 0.0337
  - Expected Return: 6.39%
  - Sharpe Ratio: 1.00
  - Asset Value: $888.30
  - Weight: 61.18%

- TSLA:

In [ ]:
<Container>
            <h1>Chatbot</h1>
            <div className='chat'>
                {chat.map((chatMessage, index) => (
                    <div key={index} className={`message ${chatMessage.isUser ? 'user' : 'chatbot'}`}>
                        {chatMessage.message}
                    </div>
                ))}
            </div>
            <Form onSubmit={(e) => { e.preventDefault(); sendMessage(); }}>
                <Form.Group>
                    <Form.Control type="text" placeholder='Type your message here' value={message} onChange={(e) => setMessage(e.target.value)} />
                </Form.Group>
                <Button variant='primary' type='submit'>
                    Send
                </Button>
             </Form>
        </Container>